apiVersion: apps/v1
kind: Deployment
metadata:
  name: reputation-checker-react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reputation-checker-react
  template:
    metadata:
      labels:
        app: reputation-checker-react
    spec:
      containers:
      - name: react
        image: tkmtakada/reputation-checker-react   # Edit
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reputation-checker-react
spec:
  type: NodePort
  selector:
    app: reputation-checker-react
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      name: reputation-checker-react